name: 🚀 Ecommerce Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 📥 Pull latest code
        run: |
          cd /home/runneruser/ecommerce-backend
          git pull origin main